### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by adamrpostjr** [pipobscure/otp#11]
Is this still maintained?

**Comment by socketpair** [comment]
Seems no.

**Comment by adamrpostjr** [comment]
I am planning to create a new library for this when time frees up at work.

**Comment by adamrpostjr** [comment]
> Seems no.

https://www.npmjs.com/package/open-otp
I will do my best to maintain and update this -- probably not perfect but I will do my best to make it better over time

**Comment by pipobscure** [comment]
Yes. If there is no reply on issues, that can have a plethora of reasons. There's also a reason why emails are in the package.json
