### ISSUE TITLE
Consider using createHmac

### ISSUE THREAD

**Issue by Florian-R** [pipobscure/otp#3]
Currently, this lib use the [crypto module](https://github.com/pipobscure/otp/blob/7f11afab8876350245f971567c2fac95096bccd0/otp.js#L7)

The problem is that causes gigantic bundles when the code is bundled with Webpack (I assume the same for browserify).

Would you be open to a PR that switch to [createHmac](https://github.com/crypto-browserify/createHmac)?

Thanks a lot.

**Comment by pipobscure** [comment]
Always
