### ISSUE TITLE
totpURL doesn't work for Google Authenticator on iOS

### ISSUE THREAD

**Issue by td-krzysiek** [pipobscure/otp#8]
When I try to create barcode from totpURL and parse it in Google Authenticator, I get `The barcode 'otpauth://totp/...` is not a valid authentication token barcode.

I have to remove trailing `=` from a secret and then this is scanned fine. My solution is to create URL manually like this:

```js
const login = process.argv[2];
const name = encodeURIComponent(`Portal (${login})`);
const secret = otp.secret.slice(0, -1); // remove trailing =
const totpURL = `otpauth://totp/${name}?secret=${secret}`;
```

**Comment by pipobscure** [comment]
Thank you and sorry for the late reply. This was fixed about a year ago with v1.1.0
